services:
  firebase:
    container_name: firebase-emulator
    build:
      context: .
    ports:
      - 8080:8080 # **FIRESTORE_PORT**
      - 5001:5001 # **FUNCTIONS_PORT**
      - 9099:9099 # **AUTH_PORT**
      - 9199:9199 # **STORAGE_PORT**
      - 4000:4000 # **HOSTING_PORT**
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080" ]
      interval: 30s
      timeout: 10s
      retries: 3
    logging: # Log rotation configuration
        driver: "json-file"
        options:
            max-size: "10m"
            max-file: "5"
