#
# This source file is part of the ENGAGE-HF based on the Stanford Spezi Template Application project
#
# SPDX-FileCopyrightText: 2023 Stanford University
#
# SPDX-License-Identifier: MIT
#


name: Beta Deployment

on:
  push:
    branches:
      - main
      - cloud-functions
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Firebase Project
    uses: StanfordBDHG/.github/.github/workflows/firebase-deploy.yml@v2
    with:
        customcommand: "npm i -g eslint"
    permissions:
      contents: read
    secrets:
      GOOGLE_APPLICATION_CREDENTIALS_BASE64: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_BASE64 }}
