#
# This source file is part of the ENGAGE-HF project based on the Stanford Spezi Template Application project
#
# SPDX-FileCopyrightText: 2023 Stanford University
#
# SPDX-License-Identifier: MIT
#

name: Lint, Build and Test

on: [pull_request]

jobs:
  deploy:
    name: Lint, Build and Test Functions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: 'true'
      - name: Git LFS Pull
        run: git lfs pull
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - name: Install Dependencies
        run: npm install --prefix models --save-dev && npm install --prefix functions --save-dev
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
      - name: Build Models
        run: npm --prefix models run build
      - name: Lint
        run: npm --prefix functions run lint:strict
      - name: Build
        run: npm --prefix functions run build:excludeModels
      - name: Test
        id: test
        run: firebase emulators:exec --only auth,firestore 'npm --prefix functions run test:ci'
      - name: Regenerate Test Results
        id: test-regenerate
        run: npm --prefix functions run test:regenerate
        if: ${{ failure() && steps.test.conclusion == 'failure' }}
      - name: Archive Regenerated Test Results
        uses: actions/upload-artifact@v4
        with:
          name: test results
          path: functions/src/tests/resources
        if: ${{ failure() && steps.test-regenerate.conclusion == 'success' }}
    permissions:
      contents: read
