#
# This source file is part of the Stanford Biodesign Digital Health ENGAGE-HF open-source project
#
# SPDX-FileCopyrightText: 2023 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

name: Production Deployment

on:
  release:
    types: [published]
  workflow_dispatch:

concurrency:
  group: production
  cancel-in-progress: false

jobs:
  deployment:
    name: Production Deployment
    uses: ./.github/workflows/deployment.yml
    permissions:
      contents: read
      checks: write
      actions: read
      security-events: write
    secrets: inherit
    with:
      environment: production
  publishpackage:
    name: Publish Package
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
    defaults:
      run:
        working-directory: ./functions/models
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache-dependency-path: ./functions/models/package-lock.json
          registry-url: 'https://registry.npmjs.org'
          scope: '@stanfordbdhg'
      - name: Clean Install
        run: npm ci
      - name: Set version
        run: npm version ${{ github.event.release.tag_name }}
      - name: Build
        run: npm run build
      - name: Publish
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
