#
# This source file is part of the Stanford Biodesign Digital Health ENGAGE-HF open-source project
#
# SPDX-FileCopyrightText: 2023 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

name: Production Deployment

on:
  release:
    types: [published]
  workflow_dispatch:

concurrency:
  group: production
  cancel-in-progress: false

jobs:
  deployment:
    name: Production Deployment
    uses: ./.github/workflows/deployment.yml
    permissions:
      contents: read
      checks: write
      actions: read
      security-events: write
    secrets: inherit
    with:
      environment: production
  publishPackage:
    name: Publish Package
    uses: StanfordBDHG/.github/.github/workflows/npm-publish-package.yml@v2
    permissions:
      contents: read
      id-token: write
      packages: write
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    with:
      packageVersion: ${{ github.event.release.tag_name }}
      cacheDependencyPath: ./functions/models/package-lock.json
      workingDirectory: ./functions/models
