#
# This source file is part of the ENGAGE-HF project based on the Stanford Spezi Template Application project
#
# SPDX-FileCopyrightText: 2023 Stanford University
#
# SPDX-License-Identifier: MIT
#

name: Release Models Package

on:
  push:
    branches:
      - models-package
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    defaults:
        run:
            working-directory: ./models
    steps:
      - uses: actions/checkout@v4
        # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache-dependency-path: ./models/
          registry-url: https://npm.pkg.github.com/
          always-auth: true
          scope: '@stanfordbdhg'
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
