#
# This source file is part of the ENGAGE-HF Firebase open-source project
#
# SPDX-FileCopyrightText: 2024 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

name: Repository Standards

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  standards:
    name: Standards
    uses: SchmiedmayerLab/.github/.github/workflows/repository-standards.yml@v0.5
